@extends('layouts.app')
@section('title',$reservation->number)
@section('content')
@include('operaciones-clientes._tabs')
<div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="page-title">{{ $reservation->number }}</h1><p class="page-subtitle">{{ $reservation->client->name }} · {{ ['active'=>'Activo','cancelled'=>'Cancelado','completed'=>'Completado','expired'=>'Vencido'][$reservation->status] ?? ucfirst($reservation->status) }}</p></div><div class="flex flex-wrap gap-2"><a target="_blank" href="{{ route('apartados.ticket',$reservation) }}" class="btn-secondary">Imprimir ticket</a>@if($reservation->status==='active')@if(auth()->user()->isAdmin() || auth()->user()->hasPermission('ventas.create'))<button type="button" onclick="sendReservationToPos()" class="btn-secondary">Pasar a factura</button>@endif @if(auth()->user()->isAdmin() || auth()->user()->hasPermission('apartados.create'))<button type="button" onclick="openFullPaymentModal()" class="btn-primary">Pagar total e imprimir</button><button type="button" onclick="openReservationModal('payment-modal')" class="btn-secondary">Registrar abono</button>@endif @if(auth()->user()->isAdmin() || auth()->user()->hasPermission('apartados.cancel'))<button type="button" onclick="openReservationModal('cancel-modal')" class="btn-danger">Cancelar</button>@endif @endif</div></div>
<div class="mb-6 grid gap-3 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 bg-white p-4"><span class="text-sm text-slate-500">Total del apartado</span><strong class="mt-1 block text-2xl">C$ {{ number_format($reservation->total,2) }}</strong></div><div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><span class="text-sm text-emerald-700">Total abonado</span><strong class="mt-1 block text-2xl text-emerald-800">C$ {{ number_format($reservation->paid_amount,2) }}</strong></div><div class="rounded-2xl border border-amber-200 bg-amber-50 p-4"><span class="text-sm text-amber-700">Saldo pendiente</span><strong class="mt-1 block text-2xl text-amber-900">C$ {{ number_format($reservation->balance,2) }}</strong></div></div>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section class="card p-4 sm:p-6"><div class="mb-4 flex justify-between"><h2 class="font-bold">Artículos reservados</h2><span class="text-sm text-slate-500">{{ $reservation->items->count() }} líneas</span></div><div class="overflow-x-auto"><table class="w-full min-w-[560px]"><thead><tr><th>Artículo</th><th>Cantidad</th><th>Precio</th><th>Subtotal</th></tr></thead><tbody>@foreach($reservation->items as $item)<tr><td>{{ $item->product->name }}</td><td>{{ $item->quantity }}</td><td>C$ {{ number_format($item->unit_price,2) }}</td><td class="font-semibold">C$ {{ number_format($item->subtotal,2) }}</td></tr>@endforeach</tbody></table></div></section>
<aside class="space-y-4"><section class="card p-5"><h2 class="font-bold">Fechas</h2><dl class="mt-3 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-slate-500">Apartado</dt><dd>{{ $reservation->reserved_at->format('d/m/Y H:i') }}</dd></div><div class="flex justify-between"><dt class="text-slate-500">Vence</dt><dd>{{ $reservation->expires_at?->format('d/m/Y H:i') ?? 'Sin vencimiento' }}</dd></div></dl></section><section class="card p-5"><h2 class="font-bold">Movimientos de dinero</h2><div class="mt-3 space-y-3"><div class="flex justify-between text-sm"><span>Anticipo inicial</span><strong>C$ {{ number_format($reservation->deposit,2) }}</strong></div>@forelse($reservation->payments->sortByDesc('paid_at') as $payment)<div class="border-t border-slate-100 pt-3 text-sm"><div class="flex justify-between"><span class="{{ $payment->type==='refund'?'text-red-600':'text-emerald-700' }}">{{ $payment->type==='refund'?'Devolución':'Abono' }}</span><strong>{{ $payment->type==='refund'?'-':'+' }} C$ {{ number_format($payment->amount,2) }}</strong></div><p class="text-xs text-slate-500">{{ $payment->paid_at->format('d/m/Y H:i') }} · {{ ucfirst($payment->payment_method) }}</p></div>@empty<p class="text-sm text-slate-500">Todavía no hay abonos adicionales.</p>@endforelse</div></section></aside></div>
@if($reservation->status==='active')
<div id="payment-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/60 p-4" role="dialog"><div class="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div class="flex justify-between"><div><h2 id="payment-modal-title" class="text-xl font-bold">Registrar abono</h2><p class="text-sm text-slate-500">Saldo: C$ {{ number_format($reservation->balance,2) }}</p></div><button type="button" onclick="closeReservationModal('payment-modal')" class="h-9 w-9 rounded-full bg-slate-100">×</button></div><form method="POST" action="{{ route('apartados.pay',$reservation) }}" class="mt-5 space-y-4">@csrf<input id="print-after-payment" type="hidden" name="print_ticket" value="0"><label class="block text-sm font-semibold">Monto<input id="reservation-payment-amount" name="amount" type="number" min="0.01" max="{{ $reservation->balance }}" step="0.01" required class="input-field mt-2"></label><label class="block text-sm font-semibold">Forma de pago<select name="payment_method" class="select-field mt-2"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option></select></label><label class="block text-sm font-semibold">Referencia<input name="reference_number" class="input-field mt-2" placeholder="Opcional"></label><button id="payment-submit-label" class="btn-primary w-full justify-center">Guardar abono</button></form></div></div>
<div id="cancel-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/60 p-4" role="dialog"><div class="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><div class="flex justify-between"><div><h2 class="text-xl font-bold">Cancelar apartado</h2><p class="text-sm text-slate-500">Los artículos volverán al inventario.</p></div><button type="button" onclick="closeReservationModal('cancel-modal')" class="h-9 w-9 rounded-full bg-slate-100">×</button></div><form method="POST" action="{{ route('apartados.cancel',$reservation) }}" class="mt-5 space-y-4">@csrf @method('PATCH')<label class="block text-sm font-semibold">Motivo<textarea name="reason" required maxlength="500" rows="2" class="input-field mt-2"></textarea></label><label class="block text-sm font-semibold">Dinero a devolver <span class="font-normal text-slate-500">(máx. C$ {{ number_format($reservation->paid_amount,2) }})</span><input name="refund_amount" type="number" min="0" max="{{ $reservation->paid_amount }}" step="0.01" value="0" class="input-field mt-2"></label><label class="block text-sm font-semibold">Medio de devolución<select name="payment_method" class="select-field mt-2"><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="transfer">Transferencia</option></select></label><button class="btn-danger w-full justify-center">Confirmar cancelación</button></form></div></div>
@php
    $posReservationDraft = [
        'reservation_id' => $reservation->id,
        'client_id' => $reservation->client_id,
        'client_name' => $reservation->client->name,
        'warehouse_id' => $reservation->warehouse_id,
        'items' => $reservation->items->map(fn ($item) => ['product_id' => $item->product_id, 'quantity' => (float) $item->quantity])->values()->all(),
    ];
@endphp
<script>window.openReservationModal=id=>{const modal=document.getElementById(id);modal.classList.remove('hidden');modal.classList.add('flex')};window.closeReservationModal=id=>{const modal=document.getElementById(id);modal.classList.add('hidden');modal.classList.remove('flex')};window.openFullPaymentModal=()=>{document.getElementById('reservation-payment-amount').value=@json($reservation->balance);document.getElementById('print-after-payment').value='1';document.getElementById('payment-modal-title').textContent='Pagar saldo completo';document.getElementById('payment-submit-label').textContent='Pagar e imprimir ticket';openReservationModal('payment-modal')};window.sendReservationToPos=()=>{sessionStorage.setItem('estelipos.posReservationDraft',JSON.stringify(@json($posReservationDraft)));window.location.href=@json(route('facturacion.pos'));};</script>
@endif
@endsection
