@extends('layouts.app')
@section('hide_back', true)
@section('title', 'Detalle de usuario')
@section('content')
@php($effectivePermissions = $user->permissions())
<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-4">@if($user->profile_photo)<img src="{{ Storage::disk('public')->url($user->profile_photo) }}" class="h-16 w-16 rounded-2xl object-cover" alt="Foto de {{ $user->name }}">@else<div class="flex h-16 w-16 items-center justify-center rounded-2xl bg-indigo-100 text-2xl font-bold text-indigo-700">{{ mb_strtoupper(mb_substr($user->name,0,1)) }}</div>@endif<div><h1 class="page-title">{{ $user->name }}</h1><p class="page-subtitle">{{ $user->username ? '@'.$user->username.' · ' : '' }}{{ $user->email }}</p></div></div><div class="flex gap-2"><a class="btn-outline" href="{{ route('settings.users') }}">Volver</a><a class="btn-primary" href="{{ route('settings.users.edit',$user) }}">Editar</a></div></div>

    <div class="grid gap-6 lg:grid-cols-3">
        <section class="card p-5"><h2 class="font-semibold">Información</h2><dl class="mt-4 space-y-3 text-sm"><div><dt class="text-xs text-slate-500">Estado</dt><dd class="mt-1"><span class="{{ $user->is_active ? 'badge-success':'badge-danger' }}">{{ $user->is_active?'Activo':'Inactivo' }}</span>@if($user->force_password_change)<span class="badge-warning ml-1">Cambio de clave pendiente</span>@endif</dd></div><div><dt class="text-xs text-slate-500">Teléfono</dt><dd>{{ $user->phone ?: 'No registrado' }}</dd></div><div><dt class="text-xs text-slate-500">Creado</dt><dd>{{ $user->created_at->format('d/m/Y H:i') }}</dd></div><div><dt class="text-xs text-slate-500">Último acceso</dt><dd>{{ $user->last_login_at?->format('d/m/Y H:i') ?? 'Nunca' }}</dd></div></dl></section>
        <section class="card p-5"><h2 class="font-semibold">Roles</h2><div class="mt-4 flex flex-wrap gap-2">@forelse($user->roles as $role)<span class="badge-info">{{ $role->name }}</span>@empty<p class="text-sm text-slate-500">Sin roles asignados.</p>@endforelse</div><h3 class="mt-6 text-sm font-semibold">Permisos especiales</h3><div class="mt-2 flex flex-wrap gap-2">@forelse($user->directPermissions as $permission)<span class="badge-warning">{{ $permission->name }}</span>@empty<p class="text-sm text-slate-500">Ninguno.</p>@endforelse</div></section>
        <section class="card p-5"><h2 class="font-semibold">Acceso efectivo</h2><p class="mt-2 text-3xl font-bold text-indigo-700">{{ $effectivePermissions->count() }}</p><p class="text-sm text-slate-500">permisos totales entre roles y excepciones</p><div class="mt-4 space-y-2">@foreach($effectivePermissions->groupBy('module') as $module=>$items)<div class="flex justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span>{{ ucfirst(str_replace('_',' ',$module)) }}</span><strong>{{ $items->count() }}</strong></div>@endforeach</div></section>
    </div>

    @if($user->id !== auth()->id())
    <section class="card p-5"><h2 class="font-semibold">Acciones de seguridad</h2><div class="mt-4 flex flex-wrap items-center gap-4"><a class="btn-outline" href="{{ route('settings.users.reset-password.form',$user) }}">Restablecer contraseña</a><x-settings.confirm-action :action="route('settings.users.toggle-active',$user)" :label="$user->is_active?'Desactivar usuario':'Activar usuario'" title="Confirmar cambio de estado" :message="$user->is_active?'El usuario perderá acceso inmediatamente.':'El usuario podrá volver a iniciar sesión.'" /><x-settings.confirm-action :action="route('settings.users.destroy',$user)" method="DELETE" label="Eliminar usuario" title="Confirmar eliminación" message="Solo se eliminará si no posee historial operativo. Esta acción no se puede deshacer." variant="danger" /></div></section>
    @endif

    <section class="card overflow-hidden"><div class="border-b border-slate-200 p-5"><h2 class="font-semibold">Actividad reciente</h2><p class="text-xs text-slate-500">Acciones realizadas por o sobre esta cuenta.</p></div><div class="divide-y divide-slate-100">@forelse($activity as $log)<div class="p-4 sm:flex sm:items-center sm:justify-between"><div><p class="text-sm font-medium">{{ $log->description ?: $log->action }}</p><p class="text-xs text-slate-500">Por {{ $log->user?->name ?? 'Sistema' }} · {{ $log->ip_address ?: 'IP no registrada' }}</p></div><time class="mt-1 block text-xs text-slate-500 sm:mt-0">{{ $log->created_at->format('d/m/Y H:i') }}</time></div>@empty<div class="p-8 text-center text-sm text-slate-500">Sin actividad registrada.</div>@endforelse</div></section>
</div>
@endsection
