@php($shipment = $shipment ?? null)
<div class="space-y-6">
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
  <div class="mb-5 flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-100 font-bold text-sky-700">1</span><div><h2 class="font-bold text-slate-900">Origen del envío</h2><p class="text-sm text-slate-500">Relaciona la entrega con un cliente o factura existente.</p></div></div>
  <div class="grid gap-4 md:grid-cols-2">
    <label class="text-sm font-semibold text-slate-700">Venta relacionada<select name="sale_id" class="select-field mt-2"><option value="">Sin factura relacionada</option>@foreach($sales as $sale)<option value="{{ $sale->id }}" @selected(old('sale_id',$shipment?->sale_id)==$sale->id)>{{ $sale->invoice_number }} · C$ {{ number_format($sale->total,2) }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold text-slate-700">Cliente<select id="shipment-client" name="client_id" class="select-field mt-2"><option value="">Cliente ocasional</option>@foreach($clients as $client)<option value="{{ $client->id }}" data-name="{{ $client->name }}" data-phone="{{ $client->phone }}" @selected(old('client_id',$shipment?->client_id)==$client->id)>{{ $client->name }}{{ $client->phone ? ' · '.$client->phone : '' }}</option>@endforeach</select><span class="mt-1 block text-xs font-normal text-slate-500">Al elegirlo completamos destinatario y teléfono.</span></label>
  </div>
</section>
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
  <div class="mb-5 flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-100 font-bold text-sky-700">2</span><div><h2 class="font-bold text-slate-900">Destino y contacto</h2><p class="text-sm text-slate-500">Información necesaria para que el paquete llegue sin contratiempos.</p></div></div>
  <div class="grid gap-4 md:grid-cols-2">
    <label class="text-sm font-semibold text-slate-700">Nombre de quien recibe<input id="recipient-name" name="recipient_name" class="input-field mt-2" required value="{{ old('recipient_name',$shipment?->recipient_name) }}" placeholder="Nombre completo"></label>
    <label class="text-sm font-semibold text-slate-700">Teléfono de contacto<input id="recipient-phone" type="tel" name="recipient_phone" class="input-field mt-2" value="{{ old('recipient_phone',$shipment?->recipient_phone) }}" placeholder="8888 8888" inputmode="tel"></label>
    <label class="text-sm font-semibold text-slate-700">Departamento<select name="department" class="select-field mt-2" required><option value="">Selecciona el departamento…</option>@foreach($departments as $department)<option @selected(old('department',$shipment?->department)===$department)>{{ $department }}</option>@endforeach</select></label>
    <label class="text-sm font-semibold text-slate-700">Municipio<input name="municipality" class="input-field mt-2" value="{{ old('municipality',$shipment?->municipality) }}" placeholder="Municipio o ciudad"></label>
    <label class="text-sm font-semibold text-slate-700 md:col-span-2">Dirección de entrega<textarea name="address" rows="3" class="input-field mt-2" required placeholder="Barrio, calle, número de casa y puntos relevantes…">{{ old('address',$shipment?->address) }}</textarea></label>
    <label class="text-sm font-semibold text-slate-700 md:col-span-2">Punto de referencia <span class="font-normal text-slate-400">(opcional)</span><textarea name="reference" rows="2" class="input-field mt-2" placeholder="Frente a…, contiguo a…, casa de color…">{{ old('reference',$shipment?->reference) }}</textarea></label>
  </div>
</section>
<div class="flex items-center justify-between gap-3 rounded-2xl border border-sky-200 bg-sky-50 p-4"><div><strong class="block text-sky-900">Despacho y seguimiento</strong><span class="text-sm text-sky-700">Agencia, guía, costo, estado y notas.</span></div><button type="button" id="open-shipment-details" class="btn-secondary whitespace-nowrap">Configurar</button></div>
<div id="shipment-details-modal" class="fixed inset-0 z-50 hidden items-center justify-center bg-slate-950/60 p-3" role="dialog" aria-modal="true"><section class="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-slate-200 bg-white p-5 shadow-2xl">
  <div class="mb-5 flex items-start justify-between gap-3"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-100 font-bold text-sky-700">3</span><div><h2 class="font-bold text-slate-900">Despacho y seguimiento</h2><p class="text-sm text-slate-500">Datos de la agencia y etapa actual.</p></div></div><button type="button" id="close-shipment-details" class="h-9 w-9 shrink-0 rounded-full bg-slate-100 text-xl">×</button></div>
  <div class="grid gap-4 md:grid-cols-3"><label class="text-sm font-semibold text-slate-700">Transportista<input name="carrier" list="carrier-options" class="input-field mt-2" value="{{ old('carrier',$shipment?->carrier) }}" placeholder="Selecciona o escribe…"><datalist id="carrier-options"><option value="Cargotrans"><option value="Transagro"><option value="Bus interlocal"><option value="Mensajería propia"></datalist></label><label class="text-sm font-semibold text-slate-700">Número de guía<input name="tracking_number" class="input-field mt-2" value="{{ old('tracking_number',$shipment?->tracking_number) }}" placeholder="Código de rastreo"></label><label class="text-sm font-semibold text-slate-700">Costo de envío<div class="relative mt-2"><span class="absolute left-3 top-2.5 text-slate-500">C$</span><input type="number" step="0.01" min="0" name="shipping_cost" class="input-field pl-10" value="{{ old('shipping_cost',$shipment?->shipping_cost ?? 0) }}"></div></label></div>
  <fieldset class="mt-5"><legend class="mb-3 text-sm font-semibold text-slate-700">Estado del envío</legend><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">@foreach(['pending'=>['Pendiente','Aún sin preparar'],'prepared'=>['Preparado','Listo para salir'],'shipped'=>['Enviado','En ruta'],'delivered'=>['Entregado','Recibido'],'cancelled'=>['Cancelado','No se enviará']] as $value=>$state)<label class="cursor-pointer"><input type="radio" name="status" value="{{ $value }}" class="peer sr-only" @checked(old('status',$shipment?->status ?? 'pending')===$value)><span class="block rounded-xl border border-slate-200 p-3 transition peer-checked:border-sky-600 peer-checked:bg-sky-50 peer-checked:ring-2 peer-checked:ring-sky-100"><strong class="block text-sm text-slate-800">{{ $state[0] }}</strong><small class="text-slate-500">{{ $state[1] }}</small></span></label>@endforeach</div></fieldset>
  <label class="mt-5 block text-sm font-semibold text-slate-700">Notas internas<textarea name="notes" rows="3" class="input-field mt-2" placeholder="Indicaciones para el equipo…">{{ old('notes',$shipment?->notes) }}</textarea></label>
</section></div>
</div>
<script>document.addEventListener('DOMContentLoaded',()=>{const client=document.getElementById('shipment-client'),modal=document.getElementById('shipment-details-modal'),toggle=show=>{modal.classList.toggle('hidden',!show);modal.classList.toggle('flex',show)};client?.addEventListener('change',()=>{const option=client.selectedOptions[0];if(!option?.value)return;const name=document.getElementById('recipient-name'),phone=document.getElementById('recipient-phone');if(!name.value)name.value=option.dataset.name||'';if(!phone.value)phone.value=option.dataset.phone||'';});document.getElementById('open-shipment-details')?.addEventListener('click',()=>toggle(true));document.getElementById('close-shipment-details')?.addEventListener('click',()=>toggle(false));modal?.addEventListener('click',event=>{if(event.target===modal)toggle(false)});});</script>
