@extends('layouts.app')
@section('title','Roles y permisos')
@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="page-title">Roles y permisos</h1><p class="page-subtitle">Perfiles únicos con acceso verificable por módulo y acción.</p></div><div class="flex gap-2"><a class="btn-outline justify-center" href="{{ route('settings.roles.compare') }}">Comparar</a><a class="btn-primary justify-center" href="{{ route('settings.roles.create') }}">+ Nuevo rol</a></div></div>
    <div class="grid grid-cols-1 gap-3 sm:grid-cols-3">@foreach(['total'=>'Total','system'=>'Sistema','custom'=>'Personalizados'] as $key=>$label)<div class="card p-4"><p class="text-xs text-slate-500">{{ $label }}</p><p class="mt-1 text-2xl font-bold">{{ $counts[$key] }}</p></div>@endforeach</div>
    <form class="card grid gap-3 p-4 sm:grid-cols-[minmax(0,1fr)_180px_auto]" method="GET"><input class="input-field" name="search" value="{{ request('search') }}" placeholder="Buscar nombre, slug o descripción"><select class="select-field" name="type"><option value="">Todos los tipos</option><option value="system" @selected(request('type')==='system')>Sistema</option><option value="custom" @selected(request('type')==='custom')>Personalizados</option></select><div class="flex gap-2"><button class="btn-primary flex-1 justify-center">Filtrar</button>@if(request()->hasAny(['search','type']))<a class="btn-outline" href="{{ route('settings.roles') }}">Limpiar</a>@endif</div></form>
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($roles as $role)<article class="card p-5"><div class="flex items-start justify-between gap-3"><div><div class="flex flex-wrap items-center gap-2"><h2 class="font-bold text-slate-900">{{ $role->name }}</h2><span class="{{ $role->is_system?'badge-info':'badge-success' }}">{{ $role->is_system?'Sistema':'Personalizado' }}</span></div><p class="mt-1 font-mono text-xs text-slate-500">{{ $role->slug }}</p></div><div class="rounded-xl bg-indigo-50 px-3 py-2 text-center"><strong class="block text-indigo-700">{{ $role->permissions->count() }}</strong><span class="text-[10px] text-indigo-600">permisos</span></div></div><p class="mt-4 min-h-10 text-sm text-slate-600">{{ $role->description ?: 'Sin descripción.' }}</p><div class="mt-4 flex items-center justify-between border-t border-slate-100 pt-4"><span class="text-xs text-slate-500">{{ $role->users_count }} usuario(s)</span><div class="flex gap-3"><a class="text-sm font-medium text-indigo-600" href="{{ route('settings.roles.show',$role) }}">Ver</a><a class="text-sm text-slate-600" href="{{ route('settings.roles.edit',$role) }}">Matriz</a><a class="text-sm text-cyan-700" href="{{ route('settings.roles.clone.form',$role) }}">Clonar</a></div></div></article>@empty<div class="card p-10 text-center text-slate-500 md:col-span-2 xl:col-span-3">No se encontraron roles.</div>@endforelse</div>
    {{ $roles->links() }}
</div>
@endsection
