@extends('layouts.app')
@section('hide_back', true)
@section('title','Detalle del rol')
@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex items-center gap-2"><h1 class="page-title">{{ $role->name }}</h1><span class="{{ $role->is_system?'badge-info':'badge-success' }}">{{ $role->is_system?'Sistema':'Personalizado' }}</span></div><p class="page-subtitle">{{ $role->slug }} · {{ $role->description ?: 'Sin descripción' }}</p></div><div class="flex flex-wrap gap-2"><a class="btn-outline" href="{{ route('settings.roles') }}">Volver</a><a class="btn-outline" href="{{ route('settings.roles.clone.form',$role) }}">Clonar</a><a class="btn-primary" href="{{ route('settings.roles.edit',$role) }}">Editar matriz</a></div></div>
    <div class="grid gap-4 sm:grid-cols-3"><div class="card p-5"><p class="text-xs text-slate-500">Usuarios</p><p class="mt-1 text-3xl font-bold text-indigo-700">{{ $role->users_count }}</p></div><div class="card p-5"><p class="text-xs text-slate-500">Permisos</p><p class="mt-1 text-3xl font-bold text-emerald-700">{{ $role->permissions->count() }}</p></div><div class="card p-5"><p class="text-xs text-slate-500">Módulos cubiertos</p><p class="mt-1 text-3xl font-bold text-cyan-700">{{ $role->permissions->pluck('module')->unique()->count() }}</p></div></div>
    <section class="card overflow-hidden"><div class="border-b border-slate-200 p-5"><h2 class="font-semibold">Permisos efectivos del rol</h2></div><div class="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-3">@forelse($role->permissions->groupBy('module') as $module=>$permissions)<div class="rounded-xl border border-slate-200 p-4"><div class="mb-3 flex justify-between"><h3 class="font-semibold capitalize">{{ str_replace('_',' ',$module) }}</h3><span class="badge-info">{{ $permissions->count() }}</span></div><div class="space-y-2">@foreach($permissions as $permission)<div class="flex gap-2 text-sm"><span class="text-emerald-600">✓</span><span>{{ $permission->name }}</span></div>@endforeach</div></div>@empty<p class="text-sm text-slate-500">Este rol no concede permisos.</p>@endforelse</div></section>
    <section class="card overflow-hidden"><div class="border-b border-slate-200 p-5"><h2 class="font-semibold">Usuarios asignados</h2></div><div class="divide-y divide-slate-100">@forelse($role->users as $user)<a class="flex items-center justify-between p-4 hover:bg-slate-50" href="{{ route('settings.users.show',$user) }}"><div><p class="text-sm font-semibold">{{ $user->name }}</p><p class="text-xs text-slate-500">{{ $user->email }}</p></div><span class="{{ $user->is_active?'badge-success':'badge-danger' }}">{{ $user->is_active?'Activo':'Inactivo' }}</span></a>@empty<div class="p-8 text-center text-sm text-slate-500">Sin usuarios asignados.</div>@endforelse</div></section>
    @unless($role->is_system)<section class="card border-red-200 p-5"><h2 class="font-semibold text-red-800">Zona de riesgo</h2><p class="mt-1 text-sm text-red-700">La eliminación exige reasignar previamente a sus usuarios.</p><a class="mt-4 inline-flex text-sm font-semibold text-red-700" href="{{ route('settings.roles.delete.form',$role) }}">Eliminar con reasignación →</a></section>@endunless
</div>
@endsection
